// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: business.proto

package business

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Business struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	SalonName            string   `protobuf:"bytes,2,opt,name=salon_name,json=salonName,proto3" json:"salon_name"`
	PhoneNumbers         []string `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status"`
	Staff                []*Staff `protobuf:"bytes,5,rep,name=staff,proto3" json:"staff"`
	Location             string   `protobuf:"bytes,6,opt,name=location,proto3" json:"location"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	DeletedAt            string   `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Business) Reset()         { *m = Business{} }
func (m *Business) String() string { return proto.CompactTextString(m) }
func (*Business) ProtoMessage()    {}
func (*Business) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{0}
}
func (m *Business) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Business) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Business.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Business) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Business.Merge(m, src)
}
func (m *Business) XXX_Size() int {
	return m.Size()
}
func (m *Business) XXX_DiscardUnknown() {
	xxx_messageInfo_Business.DiscardUnknown(m)
}

var xxx_messageInfo_Business proto.InternalMessageInfo

func (m *Business) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Business) GetSalonName() string {
	if m != nil {
		return m.SalonName
	}
	return ""
}

func (m *Business) GetPhoneNumbers() []string {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *Business) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Business) GetStaff() []*Staff {
	if m != nil {
		return m.Staff
	}
	return nil
}

func (m *Business) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Business) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Business) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Business) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type Staff struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name"`
	PhoneNumbers         []string `protobuf:"bytes,4,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers"`
	Cost                 int64    `protobuf:"varint,5,opt,name=cost,proto3" json:"cost"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	CommentId            string   `protobuf:"bytes,7,opt,name=comment_id,json=commentId,proto3" json:"comment_id"`
	BusinessId           string   `protobuf:"bytes,8,opt,name=business_id,json=businessId,proto3" json:"business_id"`
	CalendarId           string   `protobuf:"bytes,9,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id"`
	ClientId             string   `protobuf:"bytes,10,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	MenServicesId        string   `protobuf:"bytes,11,opt,name=men_services_id,json=menServicesId,proto3" json:"men_services_id"`
	WomenServicesId      string   `protobuf:"bytes,12,opt,name=women_services_id,json=womenServicesId,proto3" json:"women_services_id"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	DeletedAt            string   `protobuf:"bytes,15,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Staff) Reset()         { *m = Staff{} }
func (m *Staff) String() string { return proto.CompactTextString(m) }
func (*Staff) ProtoMessage()    {}
func (*Staff) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{1}
}
func (m *Staff) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Staff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Staff.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Staff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staff.Merge(m, src)
}
func (m *Staff) XXX_Size() int {
	return m.Size()
}
func (m *Staff) XXX_DiscardUnknown() {
	xxx_messageInfo_Staff.DiscardUnknown(m)
}

var xxx_messageInfo_Staff proto.InternalMessageInfo

func (m *Staff) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Staff) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Staff) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Staff) GetPhoneNumbers() []string {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *Staff) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Staff) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Staff) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *Staff) GetBusinessId() string {
	if m != nil {
		return m.BusinessId
	}
	return ""
}

func (m *Staff) GetCalendarId() string {
	if m != nil {
		return m.CalendarId
	}
	return ""
}

func (m *Staff) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Staff) GetMenServicesId() string {
	if m != nil {
		return m.MenServicesId
	}
	return ""
}

func (m *Staff) GetWomenServicesId() string {
	if m != nil {
		return m.WomenServicesId
	}
	return ""
}

func (m *Staff) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Staff) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Staff) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type MenServices struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	HairCut              bool     `protobuf:"varint,2,opt,name=hair_cut,json=hairCut,proto3" json:"hair_cut"`
	BeardCut             bool     `protobuf:"varint,3,opt,name=beard_cut,json=beardCut,proto3" json:"beard_cut"`
	HairColoring         bool     `protobuf:"varint,4,opt,name=hair_coloring,json=hairColoring,proto3" json:"hair_coloring"`
	SpecialHairCut       bool     `protobuf:"varint,5,opt,name=special_hair_cut,json=specialHairCut,proto3" json:"special_hair_cut"`
	BeardColoring        bool     `protobuf:"varint,6,opt,name=beard_coloring,json=beardColoring,proto3" json:"beard_coloring"`
	BeardTrim            bool     `protobuf:"varint,7,opt,name=beard_trim,json=beardTrim,proto3" json:"beard_trim"`
	BeardShave           bool     `protobuf:"varint,8,opt,name=beard_shave,json=beardShave,proto3" json:"beard_shave"`
	FaceShave            bool     `protobuf:"varint,9,opt,name=face_shave,json=faceShave,proto3" json:"face_shave"`
	BoyHairCut           bool     `protobuf:"varint,10,opt,name=boy_hair_cut,json=boyHairCut,proto3" json:"boy_hair_cut"`
	Others               string   `protobuf:"bytes,11,opt,name=others,proto3" json:"others"`
	ClientId             string   `protobuf:"bytes,12,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenServices) Reset()         { *m = MenServices{} }
func (m *MenServices) String() string { return proto.CompactTextString(m) }
func (*MenServices) ProtoMessage()    {}
func (*MenServices) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{2}
}
func (m *MenServices) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MenServices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MenServices.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MenServices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenServices.Merge(m, src)
}
func (m *MenServices) XXX_Size() int {
	return m.Size()
}
func (m *MenServices) XXX_DiscardUnknown() {
	xxx_messageInfo_MenServices.DiscardUnknown(m)
}

var xxx_messageInfo_MenServices proto.InternalMessageInfo

func (m *MenServices) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MenServices) GetHairCut() bool {
	if m != nil {
		return m.HairCut
	}
	return false
}

func (m *MenServices) GetBeardCut() bool {
	if m != nil {
		return m.BeardCut
	}
	return false
}

func (m *MenServices) GetHairColoring() bool {
	if m != nil {
		return m.HairColoring
	}
	return false
}

func (m *MenServices) GetSpecialHairCut() bool {
	if m != nil {
		return m.SpecialHairCut
	}
	return false
}

func (m *MenServices) GetBeardColoring() bool {
	if m != nil {
		return m.BeardColoring
	}
	return false
}

func (m *MenServices) GetBeardTrim() bool {
	if m != nil {
		return m.BeardTrim
	}
	return false
}

func (m *MenServices) GetBeardShave() bool {
	if m != nil {
		return m.BeardShave
	}
	return false
}

func (m *MenServices) GetFaceShave() bool {
	if m != nil {
		return m.FaceShave
	}
	return false
}

func (m *MenServices) GetBoyHairCut() bool {
	if m != nil {
		return m.BoyHairCut
	}
	return false
}

func (m *MenServices) GetOthers() string {
	if m != nil {
		return m.Others
	}
	return ""
}

func (m *MenServices) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type WomenServices struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	HairCut              bool     `protobuf:"varint,2,opt,name=hair_cut,json=hairCut,proto3" json:"hair_cut"`
	HairColoring         bool     `protobuf:"varint,3,opt,name=hair_coloring,json=hairColoring,proto3" json:"hair_coloring"`
	EyebrowArching       bool     `protobuf:"varint,4,opt,name=eyebrow_arching,json=eyebrowArching,proto3" json:"eyebrow_arching"`
	SpecialHairCut       bool     `protobuf:"varint,5,opt,name=special_hair_cut,json=specialHairCut,proto3" json:"special_hair_cut"`
	ClientId             string   `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WomenServices) Reset()         { *m = WomenServices{} }
func (m *WomenServices) String() string { return proto.CompactTextString(m) }
func (*WomenServices) ProtoMessage()    {}
func (*WomenServices) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{3}
}
func (m *WomenServices) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WomenServices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WomenServices.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WomenServices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WomenServices.Merge(m, src)
}
func (m *WomenServices) XXX_Size() int {
	return m.Size()
}
func (m *WomenServices) XXX_DiscardUnknown() {
	xxx_messageInfo_WomenServices.DiscardUnknown(m)
}

var xxx_messageInfo_WomenServices proto.InternalMessageInfo

func (m *WomenServices) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WomenServices) GetHairCut() bool {
	if m != nil {
		return m.HairCut
	}
	return false
}

func (m *WomenServices) GetHairColoring() bool {
	if m != nil {
		return m.HairColoring
	}
	return false
}

func (m *WomenServices) GetEyebrowArching() bool {
	if m != nil {
		return m.EyebrowArching
	}
	return false
}

func (m *WomenServices) GetSpecialHairCut() bool {
	if m != nil {
		return m.SpecialHairCut
	}
	return false
}

func (m *WomenServices) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type ServiceTypeDef struct {
	MenService           *MenServices   `protobuf:"bytes,1,opt,name=men_service,json=menService,proto3" json:"men_service"`
	WomenService         *WomenServices `protobuf:"bytes,2,opt,name=women_service,json=womenService,proto3" json:"women_service"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServiceTypeDef) Reset()         { *m = ServiceTypeDef{} }
func (m *ServiceTypeDef) String() string { return proto.CompactTextString(m) }
func (*ServiceTypeDef) ProtoMessage()    {}
func (*ServiceTypeDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{4}
}
func (m *ServiceTypeDef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceTypeDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceTypeDef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServiceTypeDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceTypeDef.Merge(m, src)
}
func (m *ServiceTypeDef) XXX_Size() int {
	return m.Size()
}
func (m *ServiceTypeDef) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceTypeDef.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceTypeDef proto.InternalMessageInfo

func (m *ServiceTypeDef) GetMenService() *MenServices {
	if m != nil {
		return m.MenService
	}
	return nil
}

func (m *ServiceTypeDef) GetWomenService() *WomenServices {
	if m != nil {
		return m.WomenService
	}
	return nil
}

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{5}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Id.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return m.Size()
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAllBusinessResponse struct {
	Business             []*Business `protobuf:"bytes,1,rep,name=business,proto3" json:"business"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllBusinessResponse) Reset()         { *m = GetAllBusinessResponse{} }
func (m *GetAllBusinessResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllBusinessResponse) ProtoMessage()    {}
func (*GetAllBusinessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{6}
}
func (m *GetAllBusinessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAllBusinessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAllBusinessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAllBusinessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBusinessResponse.Merge(m, src)
}
func (m *GetAllBusinessResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAllBusinessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBusinessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBusinessResponse proto.InternalMessageInfo

func (m *GetAllBusinessResponse) GetBusiness() []*Business {
	if m != nil {
		return m.Business
	}
	return nil
}

type GetListBusinessRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListBusinessRequest) Reset()         { *m = GetListBusinessRequest{} }
func (m *GetListBusinessRequest) String() string { return proto.CompactTextString(m) }
func (*GetListBusinessRequest) ProtoMessage()    {}
func (*GetListBusinessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{7}
}
func (m *GetListBusinessRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetListBusinessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetListBusinessRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetListBusinessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListBusinessRequest.Merge(m, src)
}
func (m *GetListBusinessRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetListBusinessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListBusinessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListBusinessRequest proto.InternalMessageInfo

func (m *GetListBusinessRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetListBusinessRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*Business)(nil), "business.Business")
	proto.RegisterType((*Staff)(nil), "business.Staff")
	proto.RegisterType((*MenServices)(nil), "business.MenServices")
	proto.RegisterType((*WomenServices)(nil), "business.WomenServices")
	proto.RegisterType((*ServiceTypeDef)(nil), "business.ServiceTypeDef")
	proto.RegisterType((*Id)(nil), "business.Id")
	proto.RegisterType((*GetAllBusinessResponse)(nil), "business.GetAllBusinessResponse")
	proto.RegisterType((*GetListBusinessRequest)(nil), "business.GetListBusinessRequest")
}

func init() { proto.RegisterFile("business.proto", fileDescriptor_fb4ce4f7d40c421f) }

var fileDescriptor_fb4ce4f7d40c421f = []byte{
	// 866 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xc7, 0xf1, 0x26, 0x75, 0x5e, 0x62, 0xa7, 0x8c, 0xca, 0x62, 0x82, 0xba, 0x44, 0xa9, 0x0a,
	0x11, 0x87, 0x45, 0xda, 0x0a, 0x04, 0x12, 0x97, 0xdd, 0x2d, 0x6a, 0x23, 0x41, 0x0f, 0xde, 0xae,
	0x38, 0x5a, 0x13, 0x7b, 0xb6, 0x19, 0xc9, 0xf6, 0x18, 0xcf, 0xa4, 0x55, 0x8e, 0x5c, 0xf8, 0x08,
	0x88, 0x6f, 0xc3, 0x95, 0x1b, 0x48, 0x7c, 0x01, 0xb4, 0x7c, 0x11, 0xe4, 0x37, 0xe3, 0x7f, 0x49,
	0xba, 0xa2, 0xb7, 0xcc, 0xef, 0xf7, 0xde, 0xbc, 0xf7, 0x7e, 0xbf, 0x67, 0x3b, 0xe0, 0xad, 0x36,
	0x92, 0x67, 0x4c, 0xca, 0xd3, 0xbc, 0x10, 0x4a, 0x10, 0xa7, 0x3a, 0x4f, 0xc7, 0x51, 0xc2, 0x59,
	0xa6, 0x34, 0x3e, 0xff, 0xb5, 0x07, 0xce, 0x85, 0xa1, 0x88, 0x07, 0x3d, 0x1e, 0xfb, 0xd6, 0xcc,
	0x5a, 0x0c, 0x83, 0x1e, 0x8f, 0xc9, 0x43, 0x00, 0x49, 0x13, 0x91, 0x85, 0x19, 0x4d, 0x99, 0xdf,
	0x43, 0x7c, 0x88, 0xc8, 0x0b, 0x9a, 0x32, 0xf2, 0x08, 0xdc, 0x7c, 0x2d, 0x32, 0x16, 0x66, 0x9b,
	0x74, 0xc5, 0x0a, 0xe9, 0xdb, 0x33, 0x7b, 0x31, 0x0c, 0xc6, 0x08, 0xbe, 0xd0, 0x18, 0x39, 0x86,
	0x81, 0x54, 0x54, 0x6d, 0xa4, 0x7f, 0x84, 0xf9, 0xe6, 0x44, 0x1e, 0x43, 0x5f, 0x2a, 0x7a, 0x73,
	0xe3, 0xf7, 0x67, 0xf6, 0x62, 0x74, 0x36, 0x39, 0xad, 0x1b, 0xbe, 0x2a, 0xe1, 0x40, 0xb3, 0x64,
	0x0a, 0x4e, 0x22, 0x22, 0xaa, 0xb8, 0xc8, 0xfc, 0x01, 0x5e, 0x50, 0x9f, 0xcb, 0xf6, 0xa2, 0x82,
	0x51, 0xc5, 0xe2, 0x90, 0x2a, 0xff, 0x9e, 0x6e, 0xcf, 0x20, 0xe7, 0xaa, 0xa4, 0x37, 0x79, 0x5c,
	0xd1, 0x8e, 0xa6, 0x0d, 0xa2, 0xe9, 0x98, 0x25, 0xcc, 0xd0, 0x43, 0x4d, 0x1b, 0xe4, 0x5c, 0xcd,
	0xff, 0xb6, 0xa1, 0x8f, 0x9d, 0x1c, 0x52, 0xe5, 0x86, 0x17, 0x52, 0x75, 0x54, 0x41, 0x04, 0x55,
	0xf9, 0x18, 0x86, 0x09, 0xad, 0x58, 0xdb, 0xb4, 0x4c, 0x0d, 0xb9, 0x27, 0xd9, 0xd1, 0x01, 0xc9,
	0x08, 0x1c, 0x45, 0x42, 0x2a, 0xbf, 0x3f, 0xb3, 0x16, 0x76, 0x80, 0xbf, 0x5b, 0x32, 0x0e, 0x3a,
	0x32, 0x96, 0x1a, 0x88, 0x34, 0x65, 0x99, 0x0a, 0x79, 0x5c, 0x6b, 0xa0, 0x91, 0x65, 0x4c, 0x3e,
	0x81, 0x51, 0xa5, 0x6b, 0xc9, 0x6b, 0x11, 0xa0, 0x82, 0x74, 0x40, 0x44, 0x13, 0x96, 0xc5, 0xb4,
	0x28, 0x03, 0xb4, 0x0c, 0x50, 0x41, 0xcb, 0xb8, 0x1c, 0x47, 0x2f, 0x4c, 0x49, 0x83, 0x1e, 0x47,
	0x03, 0xcb, 0x98, 0x7c, 0x0a, 0x93, 0x94, 0x65, 0xa1, 0x64, 0xc5, 0x6b, 0x1e, 0x31, 0x2c, 0x31,
	0xc2, 0x10, 0x37, 0x65, 0xd9, 0x95, 0x41, 0x97, 0x31, 0xf9, 0x1c, 0xde, 0x7f, 0x23, 0x76, 0x23,
	0xc7, 0x18, 0x39, 0x41, 0xa2, 0x15, 0xdb, 0x75, 0xd5, 0xbd, 0xdb, 0x55, 0xef, 0x6e, 0x57, 0x27,
	0xbb, 0xae, 0xfe, 0x6c, 0xc3, 0xe8, 0x87, 0xa6, 0xdc, 0x9e, 0xb7, 0x1f, 0x81, 0xb3, 0xa6, 0xbc,
	0x08, 0xa3, 0x8d, 0x42, 0x67, 0x9d, 0xe0, 0x5e, 0x79, 0xbe, 0xdc, 0xa8, 0x52, 0x88, 0x15, 0xa3,
	0x45, 0x8c, 0x9c, 0x8d, 0x9c, 0x83, 0x40, 0x49, 0x3e, 0x02, 0x57, 0xe7, 0x89, 0x44, 0x14, 0x3c,
	0x7b, 0x85, 0xcb, 0xee, 0x04, 0x63, 0x4c, 0x36, 0x18, 0x59, 0xc0, 0x7d, 0x99, 0xb3, 0x88, 0xd3,
	0x24, 0xac, 0x8b, 0xf4, 0x31, 0xce, 0x33, 0xf8, 0x73, 0x53, 0xeb, 0x31, 0x78, 0xa6, 0x56, 0x75,
	0xdf, 0x00, 0xe3, 0x5c, 0x5d, 0xb0, 0xba, 0xf0, 0x21, 0x80, 0x0e, 0x53, 0x05, 0x4f, 0xd1, 0x7c,
	0x27, 0xd0, 0x4d, 0xbe, 0x2c, 0x78, 0x8a, 0xe6, 0x23, 0x2d, 0xd7, 0xf4, 0x35, 0x43, 0xf3, 0x9d,
	0x40, 0x67, 0x5c, 0x95, 0x08, 0x6e, 0x32, 0x8d, 0x98, 0xe1, 0x87, 0x3a, 0xbf, 0x44, 0x34, 0x3d,
	0x83, 0xf1, 0x4a, 0x6c, 0x9b, 0x5e, 0xc1, 0x5c, 0x20, 0xb6, 0x55, 0x9f, 0xc7, 0x30, 0x10, 0x6a,
	0x5d, 0xee, 0xb1, 0xb6, 0xdd, 0x9c, 0xba, 0x4b, 0x33, 0xee, 0x2e, 0xcd, 0xfc, 0x4f, 0x0b, 0xdc,
	0x1f, 0xdb, 0xa6, 0xbf, 0x8b, 0x0b, 0x7b, 0x42, 0xdb, 0x07, 0x84, 0xfe, 0x0c, 0x26, 0x6c, 0xcb,
	0x56, 0x85, 0x78, 0x13, 0xd2, 0x22, 0x5a, 0x37, 0x7e, 0x78, 0x06, 0x3e, 0xd7, 0xe8, 0x3b, 0x38,
	0xd2, 0x99, 0x68, 0xb0, 0x33, 0xd1, 0x2f, 0x16, 0x78, 0x66, 0x98, 0x97, 0xdb, 0x9c, 0x3d, 0x65,
	0x37, 0xe4, 0x2b, 0x18, 0xb5, 0xf6, 0x1d, 0x67, 0x1b, 0x9d, 0x7d, 0xd0, 0xbc, 0xe4, 0x5a, 0x4b,
	0x18, 0x40, 0xa3, 0x05, 0xf9, 0x16, 0xdc, 0xce, 0x93, 0x82, 0xf3, 0x8f, 0xce, 0x3e, 0x6c, 0x32,
	0x3b, 0xd2, 0x05, 0xe3, 0xf6, 0xe3, 0x33, 0x7f, 0x00, 0xbd, 0x65, 0xbc, 0x2b, 0xe7, 0xfc, 0x39,
	0x1c, 0x3f, 0x63, 0xea, 0x3c, 0x49, 0xaa, 0x17, 0x7d, 0xc0, 0x64, 0x2e, 0x32, 0xc9, 0xc8, 0x29,
	0xd4, 0xdf, 0x05, 0xdf, 0xc2, 0xf7, 0x30, 0x69, 0x0a, 0xd5, 0xd1, 0x75, 0xcc, 0xfc, 0x02, 0x6f,
	0xfa, 0x9e, 0x4b, 0xd5, 0x5c, 0xf5, 0xd3, 0x86, 0x49, 0x45, 0x1e, 0x40, 0x3f, 0xe1, 0x29, 0x57,
	0x58, 0xd6, 0x0e, 0xf4, 0xa1, 0x7c, 0x93, 0xe5, 0xf4, 0x95, 0x1e, 0xc2, 0x0e, 0xf0, 0xf7, 0xd9,
	0xef, 0x36, 0x4c, 0xaa, 0xec, 0x6a, 0xea, 0xaf, 0xc1, 0xbb, 0xc4, 0x27, 0xbc, 0xfe, 0x14, 0x1d,
	0xe8, 0x63, 0x7a, 0x00, 0x23, 0x5f, 0x82, 0x77, 0x8d, 0x0f, 0xff, 0x9d, 0x99, 0xad, 0xaf, 0xcb,
	0x77, 0x69, 0xae, 0xb6, 0xe4, 0x0b, 0xf0, 0x9e, 0xe2, 0x4b, 0xa1, 0x4e, 0x1b, 0x37, 0x21, 0xcb,
	0x78, 0x3f, 0xe1, 0x09, 0x4c, 0x9e, 0x31, 0x75, 0xb1, 0x5d, 0xc6, 0x6f, 0xc9, 0x38, 0xd4, 0xdc,
	0x25, 0x78, 0x5d, 0xe1, 0xc9, 0xee, 0xbd, 0xd3, 0x59, 0x03, 0xbc, 0xc5, 0xa3, 0x6b, 0xac, 0xdc,
	0xd6, 0x9c, 0x74, 0x93, 0x0e, 0xd8, 0xf1, 0x3f, 0xae, 0xfd, 0x06, 0x5c, 0x2d, 0x79, 0xe5, 0x81,
	0xd7, 0xa4, 0x5c, 0x4b, 0x56, 0x4c, 0xfd, 0xd6, 0x17, 0xb9, 0xb3, 0xdb, 0x17, 0xf7, 0xff, 0xb8,
	0x3d, 0xb1, 0xfe, 0xba, 0x3d, 0xb1, 0xfe, 0xb9, 0x3d, 0xb1, 0x7e, 0xfb, 0xf7, 0xe4, 0xbd, 0xd5,
	0x00, 0xff, 0x4c, 0x3c, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x0e, 0xb4, 0x55, 0x76, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BusinessServiceClient is the client API for BusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessServiceClient interface {
	CreateBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Business, error)
	UpdateBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Empty, error)
	DeleteBusiness(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error)
	GetByIdBusiness(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Business, error)
	GetAllBusiness(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllBusinessResponse, error)
	GetListBusiness(ctx context.Context, in *GetListBusinessRequest, opts ...grpc.CallOption) (*GetAllBusinessResponse, error)
	//----------------------------Service----------------------------------------
	CreateService(ctx context.Context, in *User, opts ...grpc.CallOption) (*ServiceTypeDef, error)
}

type businessServiceClient struct {
	cc *grpc.ClientConn
}

func NewBusinessServiceClient(cc *grpc.ClientConn) BusinessServiceClient {
	return &businessServiceClient{cc}
}

func (c *businessServiceClient) CreateBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Business, error) {
	out := new(Business)
	err := c.cc.Invoke(ctx, "/business.BusinessService/CreateBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) UpdateBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/business.BusinessService/UpdateBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) DeleteBusiness(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/business.BusinessService/DeleteBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetByIdBusiness(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Business, error) {
	out := new(Business)
	err := c.cc.Invoke(ctx, "/business.BusinessService/GetByIdBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetAllBusiness(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllBusinessResponse, error) {
	out := new(GetAllBusinessResponse)
	err := c.cc.Invoke(ctx, "/business.BusinessService/GetAllBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetListBusiness(ctx context.Context, in *GetListBusinessRequest, opts ...grpc.CallOption) (*GetAllBusinessResponse, error) {
	out := new(GetAllBusinessResponse)
	err := c.cc.Invoke(ctx, "/business.BusinessService/GetListBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) CreateService(ctx context.Context, in *User, opts ...grpc.CallOption) (*ServiceTypeDef, error) {
	out := new(ServiceTypeDef)
	err := c.cc.Invoke(ctx, "/business.BusinessService/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServiceServer is the server API for BusinessService service.
type BusinessServiceServer interface {
	CreateBusiness(context.Context, *Business) (*Business, error)
	UpdateBusiness(context.Context, *Business) (*Empty, error)
	DeleteBusiness(context.Context, *Id) (*Empty, error)
	GetByIdBusiness(context.Context, *Id) (*Business, error)
	GetAllBusiness(context.Context, *Empty) (*GetAllBusinessResponse, error)
	GetListBusiness(context.Context, *GetListBusinessRequest) (*GetAllBusinessResponse, error)
	//----------------------------Service----------------------------------------
	CreateService(context.Context, *User) (*ServiceTypeDef, error)
}

// UnimplementedBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessServiceServer struct {
}

func (*UnimplementedBusinessServiceServer) CreateBusiness(ctx context.Context, req *Business) (*Business, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) UpdateBusiness(ctx context.Context, req *Business) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) DeleteBusiness(ctx context.Context, req *Id) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) GetByIdBusiness(ctx context.Context, req *Id) (*Business, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) GetAllBusiness(ctx context.Context, req *Empty) (*GetAllBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) GetListBusiness(ctx context.Context, req *GetListBusinessRequest) (*GetAllBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListBusiness not implemented")
}
func (*UnimplementedBusinessServiceServer) CreateService(ctx context.Context, req *User) (*ServiceTypeDef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}

func RegisterBusinessServiceServer(s *grpc.Server, srv BusinessServiceServer) {
	s.RegisterService(&_BusinessService_serviceDesc, srv)
}

func _BusinessService_CreateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Business)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).CreateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/CreateBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).CreateBusiness(ctx, req.(*Business))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_UpdateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Business)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).UpdateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/UpdateBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).UpdateBusiness(ctx, req.(*Business))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_DeleteBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).DeleteBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/DeleteBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).DeleteBusiness(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetByIdBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetByIdBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/GetByIdBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetByIdBusiness(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetAllBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetAllBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/GetAllBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetAllBusiness(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetListBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetListBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/GetListBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetListBusiness(ctx, req.(*GetListBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).CreateService(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "business.BusinessService",
	HandlerType: (*BusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBusiness",
			Handler:    _BusinessService_CreateBusiness_Handler,
		},
		{
			MethodName: "UpdateBusiness",
			Handler:    _BusinessService_UpdateBusiness_Handler,
		},
		{
			MethodName: "DeleteBusiness",
			Handler:    _BusinessService_DeleteBusiness_Handler,
		},
		{
			MethodName: "GetByIdBusiness",
			Handler:    _BusinessService_GetByIdBusiness_Handler,
		},
		{
			MethodName: "GetAllBusiness",
			Handler:    _BusinessService_GetAllBusiness_Handler,
		},
		{
			MethodName: "GetListBusiness",
			Handler:    _BusinessService_GetListBusiness_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _BusinessService_CreateService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business.proto",
}

func (m *Business) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Business) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.SalonName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.SalonName)))
		i += copy(dAtA[i:], m.SalonName)
	}
	if len(m.PhoneNumbers) > 0 {
		for _, s := range m.PhoneNumbers {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	if len(m.Staff) > 0 {
		for _, msg := range m.Staff {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintBusiness(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Location) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Location)))
		i += copy(dAtA[i:], m.Location)
	}
	if len(m.CreatedAt) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.CreatedAt)))
		i += copy(dAtA[i:], m.CreatedAt)
	}
	if len(m.UpdatedAt) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.UpdatedAt)))
		i += copy(dAtA[i:], m.UpdatedAt)
	}
	if len(m.DeletedAt) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.DeletedAt)))
		i += copy(dAtA[i:], m.DeletedAt)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Staff) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Staff) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.FirstName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.FirstName)))
		i += copy(dAtA[i:], m.FirstName)
	}
	if len(m.LastName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.LastName)))
		i += copy(dAtA[i:], m.LastName)
	}
	if len(m.PhoneNumbers) > 0 {
		for _, s := range m.PhoneNumbers {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.Cost != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(m.Cost))
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	if len(m.CommentId) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.CommentId)))
		i += copy(dAtA[i:], m.CommentId)
	}
	if len(m.BusinessId) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.BusinessId)))
		i += copy(dAtA[i:], m.BusinessId)
	}
	if len(m.CalendarId) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.CalendarId)))
		i += copy(dAtA[i:], m.CalendarId)
	}
	if len(m.ClientId) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.ClientId)))
		i += copy(dAtA[i:], m.ClientId)
	}
	if len(m.MenServicesId) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.MenServicesId)))
		i += copy(dAtA[i:], m.MenServicesId)
	}
	if len(m.WomenServicesId) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.WomenServicesId)))
		i += copy(dAtA[i:], m.WomenServicesId)
	}
	if len(m.CreatedAt) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.CreatedAt)))
		i += copy(dAtA[i:], m.CreatedAt)
	}
	if len(m.UpdatedAt) > 0 {
		dAtA[i] = 0x72
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.UpdatedAt)))
		i += copy(dAtA[i:], m.UpdatedAt)
	}
	if len(m.DeletedAt) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.DeletedAt)))
		i += copy(dAtA[i:], m.DeletedAt)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *MenServices) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MenServices) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.HairCut {
		dAtA[i] = 0x10
		i++
		if m.HairCut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.BeardCut {
		dAtA[i] = 0x18
		i++
		if m.BeardCut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.HairColoring {
		dAtA[i] = 0x20
		i++
		if m.HairColoring {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.SpecialHairCut {
		dAtA[i] = 0x28
		i++
		if m.SpecialHairCut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.BeardColoring {
		dAtA[i] = 0x30
		i++
		if m.BeardColoring {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.BeardTrim {
		dAtA[i] = 0x38
		i++
		if m.BeardTrim {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.BeardShave {
		dAtA[i] = 0x40
		i++
		if m.BeardShave {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.FaceShave {
		dAtA[i] = 0x48
		i++
		if m.FaceShave {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.BoyHairCut {
		dAtA[i] = 0x50
		i++
		if m.BoyHairCut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Others) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Others)))
		i += copy(dAtA[i:], m.Others)
	}
	if len(m.ClientId) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.ClientId)))
		i += copy(dAtA[i:], m.ClientId)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *WomenServices) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WomenServices) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.HairCut {
		dAtA[i] = 0x10
		i++
		if m.HairCut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.HairColoring {
		dAtA[i] = 0x18
		i++
		if m.HairColoring {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.EyebrowArching {
		dAtA[i] = 0x20
		i++
		if m.EyebrowArching {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.SpecialHairCut {
		dAtA[i] = 0x28
		i++
		if m.SpecialHairCut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.ClientId) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.ClientId)))
		i += copy(dAtA[i:], m.ClientId)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ServiceTypeDef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceTypeDef) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MenService != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(m.MenService.Size()))
		n1, err1 := m.MenService.MarshalTo(dAtA[i:])
		if err1 != nil {
			return 0, err1
		}
		i += n1
	}
	if m.WomenService != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(m.WomenService.Size()))
		n2, err2 := m.WomenService.MarshalTo(dAtA[i:])
		if err2 != nil {
			return 0, err2
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Id) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Id) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *GetAllBusinessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAllBusinessResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Business) > 0 {
		for _, msg := range m.Business {
			dAtA[i] = 0xa
			i++
			i = encodeVarintBusiness(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *GetListBusinessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetListBusinessRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(m.Limit))
	}
	if m.Page != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBusiness(dAtA, i, uint64(m.Page))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintBusiness(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Business) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.SalonName)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if len(m.PhoneNumbers) > 0 {
		for _, s := range m.PhoneNumbers {
			l = len(s)
			n += 1 + l + sovBusiness(uint64(l))
		}
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if len(m.Staff) > 0 {
		for _, e := range m.Staff {
			l = e.Size()
			n += 1 + l + sovBusiness(uint64(l))
		}
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.DeletedAt)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Staff) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.FirstName)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.LastName)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if len(m.PhoneNumbers) > 0 {
		for _, s := range m.PhoneNumbers {
			l = len(s)
			n += 1 + l + sovBusiness(uint64(l))
		}
	}
	if m.Cost != 0 {
		n += 1 + sovBusiness(uint64(m.Cost))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.CommentId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.BusinessId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.CalendarId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.MenServicesId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.WomenServicesId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.DeletedAt)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MenServices) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.HairCut {
		n += 2
	}
	if m.BeardCut {
		n += 2
	}
	if m.HairColoring {
		n += 2
	}
	if m.SpecialHairCut {
		n += 2
	}
	if m.BeardColoring {
		n += 2
	}
	if m.BeardTrim {
		n += 2
	}
	if m.BeardShave {
		n += 2
	}
	if m.FaceShave {
		n += 2
	}
	if m.BoyHairCut {
		n += 2
	}
	l = len(m.Others)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WomenServices) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.HairCut {
		n += 2
	}
	if m.HairColoring {
		n += 2
	}
	if m.EyebrowArching {
		n += 2
	}
	if m.SpecialHairCut {
		n += 2
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ServiceTypeDef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MenService != nil {
		l = m.MenService.Size()
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.WomenService != nil {
		l = m.WomenService.Size()
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Id) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBusiness(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetAllBusinessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Business) > 0 {
		for _, e := range m.Business {
			l = e.Size()
			n += 1 + l + sovBusiness(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetListBusinessRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovBusiness(uint64(m.Limit))
	}
	if m.Page != 0 {
		n += 1 + sovBusiness(uint64(m.Page))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBusiness(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBusiness(x uint64) (n int) {
	return sovBusiness(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Business) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Business: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Business: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SalonName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SalonName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhoneNumbers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhoneNumbers = append(m.PhoneNumbers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staff", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staff = append(m.Staff, &Staff{})
			if err := m.Staff[len(m.Staff)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeletedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Staff) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Staff: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Staff: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhoneNumbers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhoneNumbers = append(m.PhoneNumbers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CalendarId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CalendarId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MenServicesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MenServicesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WomenServicesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WomenServicesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeletedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MenServices) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MenServices: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MenServices: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HairCut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HairCut = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeardCut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BeardCut = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HairColoring", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HairColoring = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecialHairCut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SpecialHairCut = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeardColoring", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BeardColoring = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeardTrim", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BeardTrim = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeardShave", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BeardShave = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaceShave", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FaceShave = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoyHairCut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BoyHairCut = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Others", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Others = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WomenServices) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WomenServices: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WomenServices: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HairCut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HairCut = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HairColoring", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HairColoring = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EyebrowArching", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EyebrowArching = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecialHairCut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SpecialHairCut = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceTypeDef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceTypeDef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceTypeDef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MenService", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MenService == nil {
				m.MenService = &MenServices{}
			}
			if err := m.MenService.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WomenService", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WomenService == nil {
				m.WomenService = &WomenServices{}
			}
			if err := m.WomenService.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Id) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Id: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Id: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAllBusinessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAllBusinessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAllBusinessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Business", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBusiness
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBusiness
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Business = append(m.Business, &Business{})
			if err := m.Business[len(m.Business)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetListBusinessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetListBusinessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetListBusinessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBusiness(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBusiness
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBusiness(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBusiness
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBusiness
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBusiness
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthBusiness
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBusiness
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBusiness(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthBusiness
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBusiness = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBusiness   = fmt.Errorf("proto: integer overflow")
)
